name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: ["*"]
jobs:
  node-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

  django-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r django-ci-cd/requirements.txt
      - name: Run Django tests
        run: python django-ci-cd/manage.py test --settings=myproject.settings.ci
